// Данные генеалогического древо. Источник — архив разговоров апрель 2026.
// Каждый человек: id, display name, full name, dates, profession, place, notes, line, certain.
// line: maternal-tkachev | maternal-fedorov | maternal-samusev | paternal-vorobyov | orlov | bridge
// certain: true = подтверждено документами или прямым свидетельством
//          false = записано как слух / предположение / имя под вопросом

const people = [
  // ————————————————— Я и родители —————————————————
  {
    id: 'vladlena',
    name: 'Владлена Орлова',
    fullName: 'Орлова Владлена',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Та, кто собирает этот архив.',
    line: 'you',
    gen: 0,
    certain: true,
  },
  {
    id: 'zhanna',
    name: 'Жанна Орлова',
    fullName: 'Орлова (Ткачёва) Жанна Валерьевна',
    birth: '',
    death: '',
    profession: '',
    place: 'крещена Натальей Самусёвой в хлеву, июль 1970',
    notes: 'Мать Владлены. Хранит одну из золотых монет, переданных по линии Наталья → Тамара → Жанна.',
    line: 'bridge',
    gen: 1,
    certain: true,
  },
  {
    id: 'orlov-father',
    name: 'Орлов (отец)',
    fullName: 'Орлов ?',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Отец Владлены. Отцовская линия Орловых — Том II архива, пока не исследована. Возможная ветка уходит в Воробьёвых (Багаряк, Урал).',
    line: 'orlov',
    gen: 1,
    certain: false,
  },

  // ————————————————— МАТЕРИНСКАЯ ЛИНИЯ · Бабушка и дедушка —————————————————
  {
    id: 'valeriy',
    name: 'Валерий Ткачёв',
    fullName: 'Ткачёв Валерий Кондратович',
    birth: '',
    death: '',
    profession: '',
    place: 'Липиничи',
    notes: 'Дед Владлены по маме. Ездил к будущей жене Тамаре в Струки каждый день на велосипеде через поля.',
    line: 'maternal-tkachev',
    gen: 2,
    certain: true,
  },
  {
    id: 'tamara',
    name: 'Тамара Фёдорова',
    fullName: 'Ткачёва (Фёдорова) Тамара Васильевна',
    birth: '',
    death: '',
    profession: '',
    place: 'Струки',
    notes: 'Бабушка Владлены. В 3–4 года её хотели удочерить Иван-лётчик и Мария-радистка Самусёвы.',
    line: 'maternal-fedorov',
    gen: 2,
    certain: true,
  },
  {
    id: 'oleg',
    name: 'Олег Ткачёв',
    fullName: 'Ткачёв Олег Валерьевич',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Дядя Владлены, брат Жанны.',
    line: 'maternal-tkachev',
    gen: 1,
    certain: true,
  },
  {
    id: 'oleg-wife',
    name: 'Жена Олега',
    fullName: '?',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Имя пока не зафиксировано в архиве.',
    line: 'bridge',
    gen: 1,
    certain: false,
  },
  {
    id: 'matvey',
    name: 'Матвей Ткачёв',
    fullName: 'Ткачёв Матвей Олегович',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Двоюродный брат Владлены.',
    line: 'maternal-tkachev',
    gen: 0,
    certain: true,
  },
  {
    id: 'timofey',
    name: 'Тимофей Ткачёв',
    fullName: 'Ткачёв Тимофей Олегович',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Двоюродный брат Владлены.',
    line: 'maternal-tkachev',
    gen: 0,
    certain: true,
  },

  // ————————————————— ТКАЧЁВЫ · Прадед и прабабушка —————————————————
  {
    id: 'kondrat',
    name: 'Кондрат Ткачёв',
    fullName: 'Ткачёв Кондрат Иванович',
    birth: '1914',
    death: '16.01.1944',
    profession: 'председатель сельсовета, красноармеец, партизан',
    place: 'Липиничи, Буда-Кошелёвский р-н',
    notes: 'До войны — председатель сельсовета. Партизан 108-го отряда им. Г.И. Котовского (1-я Буда-Кошелёвская бригада). Стрелок 1201 СП 354-й стрелковой Калинковичской дивизии. Кандидат ВКП(б). Убит у д. Корени (Полесская обл., Домановичский р-н). Семейная память говорила «погиб в 43-м при переправе через Сож» — на самом деле 16.01.1944 у реки Ипа. Папа говорил, что воевал вместе с Лавриновичем — отдельный след.',
    line: 'maternal-tkachev',
    gen: 3,
    certain: true,
    links: [
      { title: 'Учётная карточка в ОБД «Мемориал»', url: 'https://obd-memorial.ru/html/info.htm?id=54637826' },
    ],
  },
  {
    id: 'matryona',
    name: 'Матрёна Беланова',
    fullName: 'Беланова Матрёна Борисовна',
    birth: '',
    death: '1974',
    profession: 'учительница',
    place: 'Гавли (р.), Липиничи (после замужества)',
    notes: 'Прабабушка Владлены. Родилась в Гавлях, после замужества семья жила в Лепинках (Липиничах). После гибели Кондрата вышла замуж за своего ученика-музыканта, на 12 лет моложе.',
    line: 'maternal-tkachev',
    gen: 3,
    certain: true,
  },
  {
    id: 'dmitry-kozlov',
    name: 'Дмитрий Козлов',
    fullName: 'Козлов Дмитрий Борисович',
    birth: '',
    death: '',
    profession: 'музыкант',
    place: 'Снежинск',
    notes: 'Второй муж Матрёны Белановой. Её ученик, на 12 лет младше. Жили в закрытом уральском городе Снежинске.',
    line: 'maternal-tkachev',
    gen: 3,
    certain: true,
  },
  {
    id: 'gennady',
    name: 'Геннадий Ткачёв',
    fullName: 'Ткачёв Геннадий Кондратович',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Старший сын Кондрата и Матрёны, брат Валерия.',
    line: 'maternal-tkachev',
    gen: 2,
    certain: true,
  },
  {
    id: 'vovka-kozlov',
    name: 'Владимир Козлов',
    fullName: 'Козлов Владимир Дмитриевич',
    birth: '',
    death: '',
    profession: '',
    place: 'Снежинск',
    notes: 'Сын Матрёны от второго мужа Дмитрия Козлова. Единоутробный брат Валерия и Геннадия. Рос при свекрови бабушки-папиной-мамы, пока мать с отчимом работали.',
    line: 'maternal-tkachev',
    gen: 2,
    certain: true,
  },
  {
    id: 'sashka-kozlov',
    name: 'Александр Козлов',
    fullName: 'Козлов Александр Дмитриевич',
    birth: '',
    death: '',
    profession: '',
    place: 'Снежинск',
    notes: 'Сын Матрёны и Дмитрия Козлова. Единоутробный брат Валерия и Геннадия.',
    line: 'maternal-tkachev',
    gen: 2,
    certain: true,
  },

  // ————————————————— ТКАЧЁВЫ · Прапрадед и прапрабабушка —————————————————
  {
    id: 'ivan-tkachev',
    name: 'Иван Ткачёв',
    fullName: 'Ткачёв Иван',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Отец Кондрата — известен только по отчеству «Иванович» в карточке ОБД «Мемориал».',
    line: 'maternal-tkachev',
    gen: 4,
    certain: false,
  },
  {
    id: 'kondrat-mother',
    name: 'Мать Кондрата',
    fullName: '?',
    birth: '',
    death: '',
    profession: '',
    place: 'Гавли',
    notes: 'Имя неизвестно. Мать Кондрата Ткачёва. Жила в Гавлях (Потаповский сельсовет, 13 км с-з от Буда-Кошелёво).',
    line: 'maternal-tkachev',
    gen: 4,
    certain: false,
  },

  // ————————————————— ФЁДОРОВЫ · Прадед и прабабушка —————————————————
  {
    id: 'vasiliy-fedorov',
    name: 'Василий Фёдоров',
    fullName: 'Фёдоров Василий Артёмович',
    birth: 'январь 1898',
    death: '',
    profession: 'портной, топил печи в школе',
    place: 'Струки',
    notes: 'Прадед Владлены. Хромал с детства. Шил полушубки по собственной системе кроя — верёвочкой измерял запястье, это был модуль. В оккупацию немцы заняли их дом под огромной липой; Наталья с ним и девятью детьми жили в бане, откуда Наталья пекла хлеб партизанам. Обстоятельства «гибели деда Василя» — открытый вопрос. Фраза мамы Жанны про него: «Мужчина — это случайно выживший мальчик».',
    line: 'maternal-fedorov',
    gen: 3,
    certain: true,
  },
  {
    id: 'natalya-samuseva',
    name: 'Наталья Самусёва',
    fullName: 'Фёдорова (Самусёва) Наталья Васильевна',
    birth: '03.08.1903',
    death: '',
    profession: 'знахарка, травница',
    place: 'Люшев',
    notes: 'Прабабушка Владлены. Пекла хлеб партизанам под носом у немецких оккупантов. Язычница, но почитала Рождество, Пасху и земледельческие праздники. Лечила заговорами и травами, к ней приходили за советом. Крестила Жанну в хлеву в июле 1970. Отцовская ветка — Самусёвы из Люшева с польско-шляхетскими корнями; мать Натальи умерла в родах, росла с отцом и мачехой.',
    line: 'maternal-samusev',
    gen: 3,
    certain: true,
  },

  // ————————————————— ФЁДОРОВЫ · Прапрадед и его брат —————————————————
  {
    id: 'artem-fedorov',
    name: 'Артём Фёдоров',
    fullName: 'Фёдоров Артём',
    birth: '',
    death: '',
    profession: 'кузнец',
    place: 'Струки',
    notes: 'Прапрадед Владлены. Зажиточный деревенский кузнец. Раскулачен в 1929–1931.',
    line: 'maternal-fedorov',
    gen: 4,
    certain: true,
  },
  {
    id: 'efim-fedorov',
    name: 'Ефим Фёдоров',
    fullName: 'Фёдоров Ефим Артёмович',
    birth: '',
    death: '',
    profession: 'советский чиновник',
    place: 'Струки, жил через двор от брата',
    notes: 'Брат Василия. Состоятельный. Дожил почти до 100 лет. Семья помнит его большой дом с резной дубовой мебелью. Всегда помогал семье брата после гибели Василя. Детей, по семейной памяти, не было.',
    line: 'maternal-fedorov',
    gen: 3,
    certain: true,
  },

  // ————————————————— 9 детей Василия и Натальи —————————————————
  {
    id: 'nikolay-f',
    name: 'Николай Фёдоров',
    fullName: 'Фёдоров Николай Васильевич',
    birth: '',
    death: '',
    profession: 'железнодорожник (жд техникум)',
    place: '',
    notes: 'Один из девяти детей Василия и Натальи.',
    line: 'maternal-fedorov',
    gen: 2,
    certain: true,
  },
  {
    id: 'anna-f',
    name: 'Анна Фёдорова',
    fullName: 'Фёдорова Анна Васильевна',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Одна из девяти детей Василия и Натальи.',
    line: 'maternal-fedorov',
    gen: 2,
    certain: true,
  },
  {
    id: 'volodya-f',
    name: 'Владимир Фёдоров',
    fullName: 'Фёдоров Владимир Васильевич',
    birth: '',
    death: '',
    profession: 'строитель',
    place: '',
    notes: 'Один из девяти детей Василия и Натальи. Не путать с Володей Самусёвым-лётчиком (сводным братом Натальи).',
    line: 'maternal-fedorov',
    gen: 2,
    certain: true,
  },
  {
    id: 'ivan-f',
    name: 'Иван Фёдоров',
    fullName: 'Фёдоров Иван Васильевич',
    birth: '',
    death: '',
    profession: 'моряк (мореходка)',
    place: 'Калининград',
    notes: 'Один из девяти детей Василия и Натальи. После мореходки жил в Калининграде.',
    line: 'maternal-fedorov',
    gen: 2,
    certain: true,
  },
  {
    id: 'grisha-f',
    name: 'Георгий Фёдоров',
    fullName: 'Фёдоров Георгий (Гриша) Васильевич',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Один из девяти детей. В октябре 2025 мама назвала «Георгий»; в апреле 2026 — «Гриша». Предположительно один и тот же человек.',
    line: 'maternal-fedorov',
    gen: 2,
    certain: false,
  },
  {
    id: 'leonid-f',
    name: 'Леонид Фёдоров',
    fullName: 'Фёдоров Леонид Васильевич',
    birth: '',
    death: '',
    profession: 'гармонист',
    place: '',
    notes: 'Один из девяти детей. У него четверо детей: Люба, Таня, Игорь, Света — все повара. Живая троюродная ветка для Владлены.',
    line: 'maternal-fedorov',
    gen: 2,
    certain: true,
  },
  {
    id: 'viktor-f',
    name: 'Виктор Фёдоров',
    fullName: 'Фёдоров Виктор Васильевич',
    birth: '',
    death: '',
    profession: 'строитель',
    place: '',
    notes: 'Один из девяти детей.',
    line: 'maternal-fedorov',
    gen: 2,
    certain: true,
  },
  {
    id: 'alexander-f',
    name: 'Александр Фёдоров',
    fullName: 'Фёдоров Александр Васильевич',
    birth: '',
    death: '',
    profession: 'автотехникум',
    place: '',
    notes: 'Один из девяти детей.',
    line: 'maternal-fedorov',
    gen: 2,
    certain: true,
  },

  // ————————————————— Дети Леонида (троюродные) —————————————————
  {
    id: 'lyuba-f',
    name: 'Люба',
    fullName: 'Фёдорова Любовь Леонидовна',
    birth: '',
    death: '',
    profession: 'повар',
    place: '',
    notes: 'Дочь Леонида Фёдорова.',
    line: 'maternal-fedorov',
    gen: 1,
    certain: true,
  },
  {
    id: 'tanya-f',
    name: 'Таня',
    fullName: 'Фёдорова Татьяна Леонидовна',
    birth: '',
    death: '',
    profession: 'повар',
    place: '',
    notes: 'Дочь Леонида Фёдорова.',
    line: 'maternal-fedorov',
    gen: 1,
    certain: true,
  },
  {
    id: 'igor-f',
    name: 'Игорь',
    fullName: 'Фёдоров Игорь Леонидович',
    birth: '',
    death: '',
    profession: 'повар',
    place: '',
    notes: 'Сын Леонида Фёдорова.',
    line: 'maternal-fedorov',
    gen: 1,
    certain: true,
  },
  {
    id: 'sveta-f',
    name: 'Света',
    fullName: 'Фёдорова Светлана Леонидовна',
    birth: '',
    death: '',
    profession: 'повар',
    place: '',
    notes: 'Дочь Леонида Фёдорова.',
    line: 'maternal-fedorov',
    gen: 1,
    certain: true,
  },

  // ————————————————— САМУСЁВЫ · Отец Натальи и семья —————————————————
  {
    id: 'samusev-father',
    name: 'Отец Натальи Самусёвой',
    fullName: 'Самусёв ?',
    birth: '',
    death: '',
    profession: '',
    place: 'Люшев',
    notes: 'Прапрадед Владлены по ветке Самусёвых. Имя не зафиксировано чётко — в архиве есть путаница с «Василием Артёмовичем», но там скорее речь про Фёдоровых. У Самусёвых в Люшеве было хорошее хозяйство и пасека. Первая жена умерла в родах, женился второй раз на мачехе.',
    line: 'maternal-samusev',
    gen: 4,
    certain: false,
  },
  {
    id: 'natalya-mother',
    name: 'Мать Натальи',
    fullName: '?',
    birth: '',
    death: 'в родах',
    profession: '',
    place: 'Люшев',
    notes: 'Первая жена отца Натальи. Умерла в родах. Имя неизвестно.',
    line: 'maternal-samusev',
    gen: 4,
    certain: false,
  },
  {
    id: 'stepmother',
    name: 'Мачеха Натальи',
    fullName: '?',
    birth: '',
    death: '',
    profession: '',
    place: 'Люшев',
    notes: 'Вторая жена отца Натальи. От неё — сводные братья и сёстры: Аня, Дуня, Володя-лётчик. Имя неизвестно.',
    line: 'maternal-samusev',
    gen: 4,
    certain: false,
  },
  {
    id: 'ksendz',
    name: 'Дед-ксендз',
    fullName: '? (католический священник)',
    birth: '',
    death: 'расстрелян',
    profession: 'ксендз (католический священник)',
    place: 'предположительно Люшевский костёл Рождества Пресвятой Девы Марии',
    notes: 'Дед бабушки Тамары. Католический священник. Семью расстреляли — маме бабушки Тамары было 4 года. Скорее всего гражданская война или советско-польская война 1918–1921. Польско-шляхетские корни Самусёвых.',
    line: 'maternal-samusev',
    gen: 5,
    certain: false,
  },

  // ————————————————— Родные братья и сёстры Натальи —————————————————
  {
    id: 'ivan-samusev',
    name: 'Иван Самусёв',
    fullName: 'Самусёв Иван Васильевич',
    birth: '',
    death: '',
    profession: 'лётчик',
    place: 'предположительно Ленинградский фронт',
    notes: 'Родной брат Натальи. Лётчик. Муж Марии-радистки. По косвенным данным — 12-я окаэ 13-й ВА Ленинградского фронта (часть его жены). В базах «Подвига народа» прямая карточка пока не найдена. Маму мамы Жанны (Тамару) Иван и Мария хотели удочерить в её 3–4 года.',
    line: 'maternal-samusev',
    gen: 3,
    certain: true,
  },
  {
    id: 'maria-samuseva',
    name: 'Мария Самусёва',
    fullName: 'Самусёва Мария Васильевна',
    birth: '',
    death: '',
    profession: 'ефрейтор, радист-наводчик корректировочной авиации',
    place: '12 окаэ 13 ВА Ленинградского фронта',
    notes: 'Жена Ивана-лётчика Самусёва. Медаль «За оборону Ленинграда». Корректировочная авиация: сидела на радио, наводила артиллерию на цель по связи. Прошла блокаду как военнослужащая.',
    line: 'maternal-samusev',
    gen: 3,
    certain: true,
    links: [
      { title: 'Карточка в «Подвиге народа»', url: 'https://podvignaroda.ru/?#id=1532463599' },
    ],
  },
  {
    id: 'eva-samuseva',
    name: 'Ева Самусёва',
    fullName: 'Самусёва Ева Васильевна',
    birth: '',
    death: '',
    profession: '',
    place: 'Люшев',
    notes: 'Сестра Натальи. Имя Ева — католическое, типичное для польско-шляхетской традиции Люшева. Родная или сводная — ещё под вопросом.',
    line: 'maternal-samusev',
    gen: 3,
    certain: false,
  },
  {
    id: 'curly-sister',
    name: 'Старшая сестра',
    fullName: '?',
    birth: '',
    death: '',
    profession: '',
    place: 'Люшев',
    notes: 'Старшая кудрявая сестра Натальи. Имя и судьба не зафиксированы. Родная или сводная — открытый вопрос.',
    line: 'maternal-samusev',
    gen: 3,
    certain: false,
  },

  // ————————————————— Сводные братья и сёстры Натальи (от мачехи) —————————————————
  {
    id: 'volodya-samusev',
    name: 'Владимир Самусёв',
    fullName: 'Самусёв Владимир Васильевич',
    birth: '',
    death: '',
    profession: 'лётчик',
    place: 'предположительно Свердловск / Екатеринбург',
    notes: 'Сводный брат Натальи по отцу (от мачехи). Лётчик. Мама сначала называла именно Владимира — в Екатеринбурге. Позже выяснилось, что лётчиков в семье было двое: родной Иван и сводный Володя.',
    line: 'maternal-samusev',
    gen: 3,
    certain: false,
  },
  {
    id: 'anya-samuseva',
    name: 'Аня Самусёва',
    fullName: 'Самусёва Анна Васильевна',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Сводная сестра Натальи по отцу (от мачехи).',
    line: 'maternal-samusev',
    gen: 3,
    certain: true,
  },
  {
    id: 'dunya-samuseva',
    name: 'Дуня Самусёва',
    fullName: 'Самусёва Евдокия Васильевна',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Сводная сестра Натальи по отцу (от мачехи).',
    line: 'maternal-samusev',
    gen: 3,
    certain: true,
  },

  // ————————————————— ОТЦОВСКАЯ ЛИНИЯ · Воробьёвы —————————————————
  {
    id: 'grigory-vorobyov',
    name: 'Григорий Воробьёв',
    fullName: 'Воробьёв Григорий',
    birth: '',
    death: '',
    profession: '',
    place: 'Багарякский р-н, Пьянковский с/с (Урал)',
    notes: 'Прапрадед Владлены по отцу (предположительно). Отец Ивана и Николая Воробьёвых. Семья раскулачена в 1929–1931. Точные данные — в ГУ ОГАЧО, Р-941, оп. 5, д. 41, л. 82.',
    line: 'paternal-vorobyov',
    gen: 4,
    certain: false,
  },
  {
    id: 'ivan-vorobyov',
    name: 'Иван Воробьёв',
    fullName: 'Воробьёв Иван Григорьевич',
    birth: '',
    death: '',
    profession: '',
    place: 'Багарякский р-н, Пьянковский с/с',
    notes: 'Глава раскулаченной семьи Воробьёвых. Старший брат Николая. Двоюродный прадед Владлены.',
    line: 'paternal-vorobyov',
    gen: 3,
    certain: false,
  },
  {
    id: 'nikolay-vorobyov',
    name: 'Николай Воробьёв',
    fullName: 'Воробьёв Николай Григорьевич',
    birth: '~1907–1909',
    death: '',
    profession: '',
    place: 'Багарякский р-н, Пьянковский с/с (Урал). В памяти семьи — «приехали из Куйбышева»',
    notes: 'Дед Владлены по отцу (предположительно). На момент раскулачивания — 22 года, брат главы семьи. Открытая задача: узнать отчество и год рождения у бабушки и папы. Архивное дело: ГУ ОГАЧО, Р-941, оп. 5, д. 41, л. 82.',
    line: 'paternal-vorobyov',
    gen: 3,
    certain: false,
  },
  {
    id: 'paternal-grandma',
    name: 'Бабушка по отцу',
    fullName: '?',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Жена Николая Воробьёва (предположительно). Имя неизвестно. Открытая задача.',
    line: 'paternal-vorobyov',
    gen: 3,
    certain: false,
  },
  {
    id: 'orlov-parent',
    name: 'Родитель отца',
    fullName: '?',
    birth: '',
    death: '',
    profession: '',
    place: '',
    notes: 'Промежуточное звено: между Николаем Воробьёвым (предположительно) и отцом Владлены. Пол и имя пока не определены — возможно, бабушка по отцу (Орлова по браку) или ещё одна фамилия в цепочке.',
    line: 'paternal-vorobyov',
    gen: 2,
    certain: false,
  },
];

// ————————————————— БРАЧНЫЕ СОЮЗЫ —————————————————
// Каждый союз получает ID union-XX и соединяет двух супругов с их детьми.
const marriages = [
  { id: 'u-vladlena-parents', spouses: ['zhanna', 'orlov-father'], children: ['vladlena'], certain: true },
  { id: 'u-valeriy-tamara',   spouses: ['valeriy', 'tamara'],      children: ['zhanna', 'oleg'], certain: true },
  { id: 'u-oleg',              spouses: ['oleg', 'oleg-wife'],      children: ['matvey', 'timofey'], certain: true },

  { id: 'u-kondrat-matryona',  spouses: ['kondrat', 'matryona'],    children: ['gennady', 'valeriy'], certain: true },
  { id: 'u-matryona-kozlov',   spouses: ['matryona', 'dmitry-kozlov'], children: ['vovka-kozlov', 'sashka-kozlov'], certain: true },

  { id: 'u-vasiliy-natalya',   spouses: ['vasiliy-fedorov', 'natalya-samuseva'],
    children: ['nikolay-f', 'anna-f', 'volodya-f', 'ivan-f', 'grisha-f', 'leonid-f', 'viktor-f', 'tamara', 'alexander-f'],
    certain: true },

  { id: 'u-leonid',            spouses: ['leonid-f'], children: ['lyuba-f', 'tanya-f', 'igor-f', 'sveta-f'], certain: true },

  { id: 'u-ivan-maria',        spouses: ['ivan-samusev', 'maria-samuseva'], children: [], certain: true },

  // Родители Натальи — две жены отца Самусёва
  { id: 'u-samusev-1',         spouses: ['samusev-father', 'natalya-mother'],
    children: ['natalya-samuseva', 'ivan-samusev', 'eva-samuseva', 'curly-sister'], certain: false },
  { id: 'u-samusev-2',         spouses: ['samusev-father', 'stepmother'],
    children: ['volodya-samusev', 'anya-samuseva', 'dunya-samuseva'], certain: false },

  // Отец Артёма → Василий и Ефим (отца Артёма нет узлом, поэтому у них общий союз-родитель через одного Артёма без жены)
  { id: 'u-artem',             spouses: ['artem-fedorov'], children: ['vasiliy-fedorov', 'efim-fedorov'], certain: true },

  // Родители Кондрата
  { id: 'u-ivan-tkachev',      spouses: ['ivan-tkachev', 'kondrat-mother'], children: ['kondrat'], certain: false },

  // Воробьёвы
  { id: 'u-grigory-v',         spouses: ['grigory-vorobyov'], children: ['ivan-vorobyov', 'nikolay-vorobyov'], certain: false },
  { id: 'u-nikolay-v',         spouses: ['nikolay-vorobyov', 'paternal-grandma'], children: ['orlov-parent'], certain: false },
  { id: 'u-orlov-parent',      spouses: ['orlov-parent'], children: ['orlov-father'], certain: false },
];

// Справочник линий для легенды
const lineInfo = {
  'you':               { label: 'Владлена',       color: '#7c3aed' },
  'bridge':            { label: 'Связующие',     color: '#64748b' },
  'maternal-tkachev':  { label: 'Ткачёвы · Белановы (по маме)', color: '#b91c1c' },
  'maternal-fedorov':  { label: 'Фёдоровы (по маме)',           color: '#0e7490' },
  'maternal-samusev':  { label: 'Самусёвы (по маме)',           color: '#0284c7' },
  'paternal-vorobyov': { label: 'Воробьёвы (по папе)',          color: '#b45309' },
  'orlov':             { label: 'Орловы (по папе)',             color: '#a16207' },
};

window.__data = { people, marriages, lineInfo };
